# Generated by Django 3.2 on 2021-04-15 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritebook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritebook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_favorite_book', to=settings.AUTH_USER_MODEL),
        ),
    ]
