# Generated by Django 3.2 on 2021-04-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookimage_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
