# Generated by Django 3.2 on 2021-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default=1, upload_to='books/', verbose_name='Книга'),
            preserve_default=False,
        ),
    ]
